# Generated by Django 4.2.1 on 2023-05-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littlelemonapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="Category",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="cart",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
